version: 0.0
os: linux

files:
  - source: /index.html
    destination: /var/www/html
    
file_exists_behavior: OVERWRITE    
          
hooks:
  BeforeInstall:
    - location: scripts/server_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/server_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 300
      runas: root 
